In [14]:
#1. Write a Python Program to Add Two Matrices?
import numpy as np
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
np.add(x,y)

array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [22]:
#2. Write a Python Program to Multiply Two Matrices?
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
x=np.array(x)
y=np.array(y)
print(x*y,"\n\n",x@y)

[[60 56  3]
 [24 35 18]
 [28 40 81]] 

 [[114 160  60]
 [ 74  97  73]
 [119 157 112]]


In [24]:
#3. Write a Python Program to Transpose a Matrix?
x = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
x=np.array(x)
x.T

array([[12,  4,  7],
       [ 7,  5,  8],
       [ 3,  6,  9]])

In [31]:
#4. Write a Python Program to Sort Words in Alphabetic Order?
a= 'Hello this is a python program'
a=a.lower()
b=a.split()
b.sort()
b

['a', 'hello', 'is', 'program', 'python', 'this']

In [39]:
#5. Write a Python Program to Remove Punctuation From a String?
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
a= 'Hello this is @#!!!! a python program'
for i in punc:
    a=a.replace(i,'')
a

'Hello this is  a python program'